name: ScheduledRssRawler

on:
  schedule:
    - cron: '0 */3 * * *'  # 每 3 小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.5'

    - name: Install dependencies
      run: go mod tidy
      working-directory: ./api/_GrabLatestRSS

    - name: Build
      run: go build -o main
      working-directory: ./api/_GrabLatestRSS

    - name: Run Go program
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        ./main
      working-directory: ./api/_GrabLatestRSS
      continue-on-error: false  # 如果 Go 程序失败，将使工作流失败

    - name: Upload logs
      if: failure()  # 仅在工作流失败时上传日志
      uses: actions/upload-artifact@v3
      with:
        name: rss-logs
        path: ./api/_GrabLatestRSS/logs/  # 确保你在 Go 程序中有生成日志文件
